.TH tsocks 1 "Jul 2001" "tsocks"
.SH NAME
tsocks \- the wrapper to use tsocks library transparently to the application
.SH SYNOPSIS
.B tsocks
.RB [application\ [application's\ arguments]]
.br
or
.B tsocks
.RB [on|off]
.br
or
.B tsocks
.SH DESCRIPTION
.B tsocks
is the wrapper between the tsocks library and the application what you
would like to run socksified.
.SH OPTIONS
.IP \fB[application\ \fB[application's\ arguments]]
what application you'd like to socksify with what program's argumets
.IP \fB[on|off]
that is useful if you'd like to turn on or off the socksifying with
expanding or shrinking the LD_PRELOAD environment variable. If you want to
use this function, you HAVE to source that shell script from yours,
like this: "source /usr/bin/tsocks" or ". /usr/bin/tsocks"
.br
Example:
.br
". tsocks on" -- add the tsocks lib to the LD_PRELOAD
.br
". tsocks off" -- remove the tsocks lib from the LD_PRELOAD
.IP \fB[show|sh]
show the LD_PRELOAD variable
.IP \fB<without\ any\ argument>
just socksify everything from now with forking a new shell with the right
new LD_PRELOAD environment variable.
.PP
.SH AUTHOR
This crap created by Tamas SZERB <toma@rulez.org>
